#%RAML 1.0 Library

uses:
  types: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/types.raml

traits:
  formatNino:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              formatNino:
                description: 'The format of the supplied NINO field is not valid.'
                value:
                  code: FORMAT_NINO
  formatTaxYear:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              formatTaxYear:
                description: 'The format of the supplied tax year field is not valid.'
                value:
                  code: FORMAT_TAX_YEAR
  incorrectOrEmptyBody:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              incorrectOrEmptyBody:
                description: 'An empty or non-matching body was submitted.'
                value:
                  code: RULE_INCORRECT_OR_EMPTY_BODY_SUBMITTED
  ruleTaxYearNotSupported:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              rule_TaxYearNotSupported:
                description: 'The specified tax year is not supported. That is, the tax year specified is before the minimum tax year value.'
                value:
                  code: RULE_TAX_YEAR_NOT_SUPPORTED
  ruleInvalidRequest:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              ruleInvalidRequest:
                description: 'The request cannot be made as the current NINO supplied is invalid.'
                value:
                  code: RULE_INVALID_REQUEST
  ruleTaxYearRangeInvalid:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              ruleTaxYearRangeInvalid:
                description: 'Tax year range invalid. A tax year range of one year is required.'
                value:
                  code: RULE_TAX_YEAR_RANGE_INVALID
  srnInvalid:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              srnInvalid:
                description: 'The format of the supplied scheme reference number is not valid.'
                value:
                  code: FORMAT_SRN_INVALID
  voluntaryClass2Contributions:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              voluntaryClass2Contributions:
                description: 'Voluntary Class 2 Contributions can only be set to true.'
                value:
                  code: RULE_VOLUNTARY_CLASS2_VALUE_INVALID
  formatSpouseOrCivilPartnersFirstName:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              formatSpouseOrCivilPartnersFirstName:
                description: "The format of your spouse or civil partner's first name is not valid."
                value:
                  code: FORMAT_SPOUSE_OR_CIVIL_PARTNERS_FIRST_NAME
  formatSpouseOrCivilPartnersSurname:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              formatSpouseOrCivilPartnersSurname:
                description: "The format of your spouse or civil partner's surname name is not valid."
                value:
                  code: FORMAT_SPOUSE_OR_CIVIL_PARTNERS_SURNAME
  formatSpouseOrCivilPartnersNino:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              formatSpouseOrCivilPartnersNino:
                description: "The format of your spouse or civil partner's National Insurance Number is not valid."
                value:
                  code: FORMAT_SPOUSE_OR_CIVIL_PARTNERS_NINO
  formatSpouseOrCivilPartnersDateOfBirth:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              formatSpouseOrCivilPartnersDateOfBirth:
                description: "The format of the supplied spouse or civil partner's date of birth is not valid."
                value:
                  code: FORMAT_SPOUSE_OR_CIVIL_PARTNERS_DATE_OF_BIRTH
  voluntaryClass2CannotBeChanged:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              voluntaryClass2CannotBeChanged:
                description: 'Voluntary Class 2 NICs cannot be changed after 31st Jan following the year of submission.'
                value:
                  code: RULE_VOLUNTARY_CLASS2_CANNOT_BE_CHANGED
  ruleDeceasedRecipient:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              ruleDeceasedRecipient:
                description: "The supplied spouse or civil partner is invalid because they are deceased."
                value:
                  code: RULE_DECEASED_RECIPIENT
  ruleActiveMarriageAllowanceClaim:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              ruleActiveMarriageAllowanceClaim:
                description: "The request cannot be made as there is an existing Marriage Allowance claim. "
                value:
                  code: RULE_ACTIVE_MARRIAGE_ALLOWANCE_CLAIM
  clientOrAgentNotAuthorised:
    responses:
      403:
        body:
          application/json:
            type: types.errorResponse
            examples:
              clientOrAgentNotAuthorised:
                description: 'The client or agent is not authorised. This is because: the client is not subscribed to MTD, the agent is not subscribed to Agent Services, or the client has not authorised the agent to act on their behalf.'
                value:
                  code: CLIENT_OR_AGENT_NOT_AUTHORISED
  notFound:
    responses:
      404:
        body:
          application/json:
            type: types.errorResponse
            examples:
              notFound:
                description: 'The supplied income source could not be found.'
                value:
                  code: MATCHING_RESOURCE_NOT_FOUND